// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9RLp8OYCBK3LgGHk_JOM26EZOvFRqDSA',
    appId: '1:1097242726945:web:eb603014190e2ab72c8960',
    messagingSenderId: '1097242726945',
    projectId: 'jana-soz',
    authDomain: 'jana-soz.firebaseapp.com',
    storageBucket: 'jana-soz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsG1rDLmRcHtFloD3gSQfLsSH_N3rp6Gk',
    appId: '1:1097242726945:android:a727f60e5a1971992c8960',
    messagingSenderId: '1097242726945',
    projectId: 'jana-soz',
    storageBucket: 'jana-soz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg5JR_zfjHu4JypCiEWaDy8eOH43_cedk',
    appId: '1:1097242726945:ios:f28e61c3e2002b6b2c8960',
    messagingSenderId: '1097242726945',
    projectId: 'jana-soz',
    storageBucket: 'jana-soz.appspot.com',
    iosClientId: '1097242726945-r1mv5qfv4bn6u1mnnveioti2ss8mq86u.apps.googleusercontent.com',
    iosBundleId: 'com.example.janaSoz',
  );
}
